/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as BuyerActionRouteImport } from './routes/buyer-action'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotifyRouteImport } from './routes/notify'
import { Route as StoresRouteImport } from './routes/stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerActionRoute = BuyerActionRouteImport.update({
  id: '/buyer-action',
  path: '/buyer-action',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyRoute = NotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/articles': typeof ArticlesRoute
  '/buyer-action': typeof BuyerActionRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/articles': typeof ArticlesRoute
  '/buyer-action': typeof BuyerActionRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/articles': typeof ArticlesRoute
  '/buyer-action': typeof BuyerActionRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/stores': typeof StoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/articles'
    | '/buyer-action'
    | '/login'
    | '/notify'
    | '/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/articles'
    | '/buyer-action'
    | '/login'
    | '/notify'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/articles'
    | '/buyer-action'
    | '/login'
    | '/notify'
    | '/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  ArticlesRoute: typeof ArticlesRoute
  BuyerActionRoute: typeof BuyerActionRoute
  LoginRoute: typeof LoginRoute
  NotifyRoute: typeof NotifyRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-action': {
      id: '/buyer-action'
      path: '/buyer-action'
      fullPath: '/buyer-action'
      preLoaderRoute: typeof BuyerActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify': {
      id: '/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof NotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  ArticlesRoute: ArticlesRoute,
  BuyerActionRoute: BuyerActionRoute,
  LoginRoute: LoginRoute,
  NotifyRoute: NotifyRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
