/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AreaViewRouteImport } from './routes/area-view'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as BuyerActionRouteImport } from './routes/buyer-action'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotifyRouteImport } from './routes/notify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SubmissionRouteImport } from './routes/submission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaViewRoute = AreaViewRouteImport.update({
  id: '/area-view',
  path: '/area-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerActionRoute = BuyerActionRouteImport.update({
  id: '/buyer-action',
  path: '/buyer-action',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyRoute = NotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionRoute = SubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/admin': typeof AdminRoute
  '/area-view': typeof AreaViewRoute
  '/articles': typeof ArticlesRoute
  '/attention': typeof AttentionRoute
  '/buyer-action': typeof BuyerActionRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/submission': typeof SubmissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/admin': typeof AdminRoute
  '/area-view': typeof AreaViewRoute
  '/articles': typeof ArticlesRoute
  '/attention': typeof AttentionRoute
  '/buyer-action': typeof BuyerActionRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/submission': typeof SubmissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/admin': typeof AdminRoute
  '/area-view': typeof AreaViewRoute
  '/articles': typeof ArticlesRoute
  '/attention': typeof AttentionRoute
  '/buyer-action': typeof BuyerActionRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/notify': typeof NotifyRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/submission': typeof SubmissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/admin'
    | '/area-view'
    | '/articles'
    | '/attention'
    | '/buyer-action'
    | '/inspector'
    | '/login'
    | '/notify'
    | '/settings'
    | '/stores'
    | '/submission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/admin'
    | '/area-view'
    | '/articles'
    | '/attention'
    | '/buyer-action'
    | '/inspector'
    | '/login'
    | '/notify'
    | '/settings'
    | '/stores'
    | '/submission'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/admin'
    | '/area-view'
    | '/articles'
    | '/attention'
    | '/buyer-action'
    | '/inspector'
    | '/login'
    | '/notify'
    | '/settings'
    | '/stores'
    | '/submission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AdminRoute: typeof AdminRoute
  AreaViewRoute: typeof AreaViewRoute
  ArticlesRoute: typeof ArticlesRoute
  AttentionRoute: typeof AttentionRoute
  BuyerActionRoute: typeof BuyerActionRoute
  InspectorRoute: typeof InspectorRoute
  LoginRoute: typeof LoginRoute
  NotifyRoute: typeof NotifyRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  SubmissionRoute: typeof SubmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-view': {
      id: '/area-view'
      path: '/area-view'
      fullPath: '/area-view'
      preLoaderRoute: typeof AreaViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-action': {
      id: '/buyer-action'
      path: '/buyer-action'
      fullPath: '/buyer-action'
      preLoaderRoute: typeof BuyerActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify': {
      id: '/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof NotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission': {
      id: '/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AdminRoute: AdminRoute,
  AreaViewRoute: AreaViewRoute,
  ArticlesRoute: ArticlesRoute,
  AttentionRoute: AttentionRoute,
  BuyerActionRoute: BuyerActionRoute,
  InspectorRoute: InspectorRoute,
  LoginRoute: LoginRoute,
  NotifyRoute: NotifyRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  SubmissionRoute: SubmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
